### ISSUE TITLE
Gradebook update

### ISSUE THREAD

**Issue by science-code** [vvv-school/vvv18#41]
Dear Ugo @pattacini,

Would it be possible to launch the grader for the following two assignments?

Gradebook in YARP Middleware
Gradebook in Robot Dynamics

Thank you and kind regards,
Mihai

**Comment by pattacini** [comment]
Of course, gimme just the necessary time! 👍

**Comment by marco-monforte** [comment]
I would ask the same for the Event-based Vision gradebook :)

Thanks!

**Comment by pattacini** [comment]
Sure @marco-monforte 😉

**Comment by pattacini** [comment]
Done!

**Comment by science-code** [comment]
@pattacini 
Thank you!
However, I still have a problem with the assignment on YARP Middleware: I get 14/14 on my machine, but only 10/14 on the remote machine...

**Comment by pattacini** [comment]
Ehm, @science-code do you know that there's a decay function that reduces the max points on the grading machine depending on the delay of the submission?

Just kidding! Actually, I've seen this weird behavior on the physical machine, thus let me call for @Nicogene who could perhaps patch the smoke test in this respect.

**Comment by science-code** [comment]
@pattacini, @Nicogene Thank you! I will be waiting for an update from your side in this case.

**Comment by Nicogene** [comment]
Sorry guys my bad, I made some changes in `assignment_motor-control` for the next year and I didn't know that the repo was still used by the grading machine!
Now should work

**Comment by pattacini** [comment]
Grading's underway. Stay tuned.

**Comment by pattacini** [comment]
Done. Check it out ✨

**Comment by gonzalezJohnas** [comment]
Dear @pattacini ,
Could you run please the grader for : 
Yarp vision
Yarp Dynamics

Grazie mile

**Comment by pattacini** [comment]
Sure @gonzalezJohnas

**Comment by pattacini** [comment]
Done.
